version: '3.9'

services:
  elasticsearch:
    ports:
      - 9200:9200
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200

  mssqlserver:
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=y
     - SA_PASSWORD=Pass321$

  catalog.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  identity.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ordering.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:80
      - 5005:5005
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  onlinestore.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5003:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro