version: '3.4'

services:
  elasticsearch:
    ports:
      - 9200:9200
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200

  mssqlserver:
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=y
     - SA_PASSWORD=Pass321$
  
  cacheserver:
    ports:
     - 6379:6379
    environment:
     - ALLOW_EMPTY_PASSWORD=yes
  
  rabbitmq:
    ports:
     - 5672:5672
     - 15672:15672

  mongodb:
    ports:
     - 27017:27017

  catalog.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  identity.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ordering.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5003:80
      - 5006:5006
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  onlinestore.chat:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5004:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  onlinestore.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5005:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  onlinestore.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro